// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlRA43i5qsNpamlXlK3KRUScDjmwXeJo',
    appId: '1:1040943690288:web:64f6a0f302c0b6a5c1f3f5',
    messagingSenderId: '1040943690288',
    projectId: 'push-testing-5e3e0',
    authDomain: 'push-testing-5e3e0.firebaseapp.com',
    storageBucket: 'push-testing-5e3e0.appspot.com',
    measurementId: 'G-4QX99VHTQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVsagaiNylDXqBk7BKwrDcnKDlaBYzbu4',
    appId: '1:1040943690288:android:38b34385f402f68bc1f3f5',
    messagingSenderId: '1040943690288',
    projectId: 'push-testing-5e3e0',
    storageBucket: 'push-testing-5e3e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe-1j8XlNy4i62EGCmz7SakDZJUQzqfyo',
    appId: '1:1040943690288:ios:fe1cd520d18d35e4c1f3f5',
    messagingSenderId: '1040943690288',
    projectId: 'push-testing-5e3e0',
    storageBucket: 'push-testing-5e3e0.appspot.com',
    iosClientId: '1040943690288-e8ubmbst1tskj0nr2h9j1mlcci1mba4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushTesting',
  );
}
